/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Complete MCAP info output structure.
 */
export interface McapInfoOutput {
  file: FileInfo;
  header: HeaderInfo;
  statistics: StatisticsInfo;
  chunks: ChunksInfo;
  channels: ChannelInfo[];
  schemas: SchemaInfo[];
  message_distribution: MessageDistribution;
}
/**
 * File metadata.
 */
export interface FileInfo {
  path: string;
  size_bytes: number;
}
/**
 * MCAP header information.
 */
export interface HeaderInfo {
  library: string;
  profile: string;
}
/**
 * MCAP statistics.
 */
export interface StatisticsInfo {
  message_count: number;
  chunk_count: number;
  message_index_count: number | null;
  channel_count: number;
  attachment_count: number;
  metadata_count: number;
  message_start_time: number;
  message_end_time: number;
  duration_ns: number;
}
/**
 * Chunk-related information.
 */
export interface ChunksInfo {
  by_compression: {
    [k: string]: CompressionStats;
  };
  overlaps: ChunkOverlaps;
}
/**
 * Statistics for a specific compression type.
 */
export interface CompressionStats {
  count: number;
  compressed_size: number;
  uncompressed_size: number;
  compression_ratio: number;
  message_count: number;
  size_stats: Stats;
  duration_stats: Stats;
}
/**
 * Statistics with minimum, average, and maximum values.
 */
export interface Stats {
  minimum: number;
  maximum: number;
  average: number;
  median: number;
}
/**
 * Chunk overlap information.
 */
export interface ChunkOverlaps {
  max_concurrent: number;
  max_concurrent_bytes: number;
}
/**
 * Information about a channel.
 */
export interface ChannelInfo {
  id: number;
  topic: string;
  schema_id: number;
  schema_name: string | null;
  message_count: number;
  size_bytes: number | null;
  duration_ns: number | null;
  hz_stats: PartialStats;
  hz_channel: number | null;
  bytes_per_second_stats: PartialStats | null;
  bytes_per_message: number | null;
  message_distribution: number[];
  message_start_time: number | null;
  message_end_time: number | null;
}
/**
 * Statistics where only average is always available; min/max/median are only available in rebuild mode.
 */
export interface PartialStats {
  average: number;
  minimum: number | null;
  maximum: number | null;
  median: number | null;
}
/**
 * Information about a schema.
 */
export interface SchemaInfo {
  id: number;
  name: string;
}
/**
 * Message distribution across time buckets.
 */
export interface MessageDistribution {
  bucket_count: number;
  bucket_duration_ns: number;
  message_counts: number[];
  max_count: number;
}
