/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Scan depth level.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "ScanMode".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "ScanMode".
 */
export type ScanMode = "summary" | "rebuild" | "exact";

/**
 * Complete MCAP info output structure.
 */
export interface McapInfoOutput {
  file: FileInfo;
  header: HeaderInfo;
  statistics: StatisticsInfo;
  chunks: ChunksInfo;
  channels: ChannelInfo[];
  schemas: SchemaInfo[];
  message_distribution: MessageDistribution;
  metadata?: MetadataInfo[];
  attachments?: AttachmentInfo[];
  /**
   * Base64-encoded micro-thumbnail JPEG (48x36, q=0.5).
   */
  thumbnail?: string;
}
/**
 * File metadata.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "FileInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "FileInfo".
 */
export interface FileInfo {
  path: string;
  size_bytes: number;
}
/**
 * MCAP header information.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "HeaderInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "HeaderInfo".
 */
export interface HeaderInfo {
  library: string;
  profile: string;
}
/**
 * MCAP statistics.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "StatisticsInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "StatisticsInfo".
 */
export interface StatisticsInfo {
  message_count: number;
  chunk_count: number;
  message_index_count: number | null;
  channel_count: number;
  attachment_count: number;
  metadata_count: number;
  message_start_time: number;
  message_end_time: number;
  duration_ns: number;
}
/**
 * Chunk-related information.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "ChunksInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "ChunksInfo".
 */
export interface ChunksInfo {
  by_compression: {
    [k: string]: CompressionStats;
  };
  overlaps: ChunkOverlaps;
}
/**
 * Statistics for a specific compression type.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "CompressionStats".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "CompressionStats".
 */
export interface CompressionStats {
  count: number;
  compressed_size: number;
  uncompressed_size: number;
  compression_ratio: number;
  message_count: number;
  size_stats: Stats;
  duration_stats: Stats;
}
/**
 * Statistics with minimum, average, and maximum values.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "Stats".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "Stats".
 */
export interface Stats {
  minimum: number;
  maximum: number;
  average: number;
  median: number;
}
/**
 * Chunk overlap information.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "ChunkOverlaps".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "ChunkOverlaps".
 */
export interface ChunkOverlaps {
  max_concurrent: number;
  max_concurrent_bytes: number;
}
/**
 * Information about a channel.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "ChannelInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "ChannelInfo".
 */
export interface ChannelInfo {
  id: number;
  topic: string;
  schema_id: number;
  message_count: number;
  size_bytes: number | null;
  duration_ns: number | null;
  hz_stats?: IntervalStats | null;
  message_distribution?: number[];
  message_start_time?: number | null;
  message_end_time?: number | null;
  /**
   * Whether size_bytes is estimated from MessageIndex offsets (true) or measured from actual data (false).
   */
  estimated_sizes: boolean;
  /**
   * Standard deviation of inter-message intervals in nanoseconds.
   */
  jitter_ns?: number | null;
}
/**
 * Min/max/median statistics from per-interval measurements (rebuild-only).
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "IntervalStats".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "IntervalStats".
 */
export interface IntervalStats {
  minimum: number | null;
  maximum: number | null;
  median: number | null;
}
/**
 * Information about a schema.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "SchemaInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "SchemaInfo".
 */
export interface SchemaInfo {
  id: number;
  name: string;
  encoding: string;
  data: string;
}
/**
 * Message distribution across time buckets.
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "MessageDistribution".
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "MessageDistribution".
 */
export interface MessageDistribution {
  bucket_count: number;
  bucket_duration_ns: number;
  message_counts: number[];
  max_count: number;
}
/**
 * MCAP metadata record.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "MetadataInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "MetadataInfo".
 */
export interface MetadataInfo {
  name: string;
  metadata: {
    [k: string]: string;
  };
}
/**
 * MCAP attachment record.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "AttachmentInfo".
 *
 * This interface was referenced by `McapInfoOutput1`'s JSON-Schema
 * via the `definition` "AttachmentInfo".
 */
export interface AttachmentInfo {
  name: string;
  media_type: string;
  data_size: number;
  log_time: number;
  create_time: number;
  offset: number;
  length: number;
}
/**
 * Shareable URL payload wrapping McapInfoOutput with scan metadata.
 *
 * This interface was referenced by `McapInfoOutput`'s JSON-Schema
 * via the `definition` "UrlPayload".
 */
export interface UrlPayload {
  mode: ScanMode;
  /**
   * Browser-side file identifier derived from filename and size.
   */
  fileId: string;
  data: McapInfoOutput1;
}
/**
 * The McapInfoOutput data.
 */
export interface McapInfoOutput1 {
  file: FileInfo;
  header: HeaderInfo;
  statistics: StatisticsInfo;
  chunks: ChunksInfo;
  channels: ChannelInfo[];
  schemas: SchemaInfo[];
  message_distribution: MessageDistribution;
  metadata?: MetadataInfo[];
  attachments?: AttachmentInfo[];
  /**
   * Base64-encoded micro-thumbnail JPEG (48x36, q=0.5).
   */
  thumbnail?: string;
}
