"""Generate decoding code of a schema inside a MCAP.

Usage:
uv run python -m mcap_ros2_support_fast.scripts.generate_code <mcap_file> -o output.py
"""

import argparse
from pathlib import Path

from mcap_ros2_support_fast._dynamic_decoder import (
    DecoderGeneratorFactory,
)
from mcap_ros2_support_fast._dynamic_encoder import EncoderGeneratorFactory
from mcap_ros2_support_fast._planner import generate_plans, optimize_plan
from small_mcap.reader import get_summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mcap_file", help="MCAP file to read schemas from")
    parser.add_argument(
        "-o", "--output", required=True, help="Output python file to write generated code to"
    )
    parser.add_argument(
        "--endianness",
        choices=["little", "big"],
        default="little",
        help="Endianness for code generation (default: little)",
    )
    args = parser.parse_args()

    endianness = "<" if args.endianness == "little" else ">"

    output_path = Path(args.output)
    output_path.parent.mkdir(exist_ok=True, parents=True)

    # Generate code for each schema
    decoder_factories_le = []
    decoder_factories_be = []
    encoder_factories = []
    seen_schemas: set[str] = set()
    decoder_functions_le = []
    decoder_functions_be = []
    decoder_dispatchers = []
    encoder_functions = []

    with Path(args.mcap_file).open("rb") as f:
        summary = get_summary(f)
        assert summary
        schemas = summary.schemas
        for schema in schemas.values():
            if schema.name in seen_schemas:
                continue
            seen_schemas.add(schema.name)
            plan = generate_plans(schema.name, schema.data.decode())
            optimized_plan = optimize_plan(plan)

            # Create BOTH little and big-endian decoder factories
            # (decoder needs to handle both based on CDR header)
            safe_name = schema.name.replace("/", "_")

            decoder_factory_le = DecoderGeneratorFactory(optimized_plan, endianness="<")
            decoder_func_name_le = f"decode_{safe_name}_le"
            decoder_code_le = decoder_factory_le.generate_decoder_code(decoder_func_name_le)
            decoder_factories_le.append(decoder_factory_le)
            decoder_functions_le.append(decoder_code_le)

            decoder_factory_be = DecoderGeneratorFactory(optimized_plan, endianness=">")
            decoder_func_name_be = f"decode_{safe_name}_be"
            decoder_code_be = decoder_factory_be.generate_decoder_code(decoder_func_name_be)
            decoder_factories_be.append(decoder_factory_be)
            decoder_functions_be.append(decoder_code_be)

            # Create dispatcher that checks CDR header
            dispatcher = f"""def decode_{safe_name}(_raw):
    '''Decoder that dispatches based on CDR header endianness.'''
    if _raw[0] | (_raw[1] ^ 0x01):
        if _raw[0] == 0 and _raw[1] == 0x00:
            return {decoder_func_name_be}(_raw)
        _kind = (_raw[0] << 8) | _raw[1]
        raise McapROS2DecodeError(
            f"unsupported CDR encapsulation kind: {{_kind:#06x}}"
        )
    return {decoder_func_name_le}(_raw)
"""
            decoder_dispatchers.append(dispatcher)

            # Create encoder factory for this schema (only one endianness needed)
            encoder_factory = EncoderGeneratorFactory(optimized_plan, endianness=endianness)
            encoder_func_name = f"encode_{safe_name}"
            encoder_code = encoder_factory.generate_encoder_code(encoder_func_name)

            encoder_factories.append(encoder_factory)
            encoder_functions.append(encoder_code)

    # Extract information needed for code generation
    all_decoder_struct_patterns = {}
    all_encoder_struct_patterns = {}
    all_message_classes = set()

    for decoder_factory in decoder_factories_le:
        all_decoder_struct_patterns.update(decoder_factory.struct_patterns)
        all_message_classes.update(decoder_factory.message_classes)

    for decoder_factory in decoder_factories_be:
        all_decoder_struct_patterns.update(decoder_factory.struct_patterns)
        all_message_classes.update(decoder_factory.message_classes)

    for encoder_factory in encoder_factories:
        all_encoder_struct_patterns.update(encoder_factory.struct_patterns)
        all_message_classes.update(encoder_factory.message_classes)

    # Start building the complete output file
    generated_lines = [
        "# ruff: noqa",
        '"""This file is autogenerated, do not edit."""',
        "",
        "# Imports",
        "import array",
        "import dataclasses",
        "import struct",
        "import sys",
        "import typing",
        "import collections.abc",
        "",
    ]

    # Add utility function definitions
    generated_lines.extend(
        [
            "# Utility functions",
            "_PADS = (b'', b'\\x00', b'\\x00\\x00', b'\\x00\\x00\\x00',",
            "         b'\\x00\\x00\\x00\\x00', b'\\x00\\x00\\x00\\x00\\x00',",
            "         b'\\x00\\x00\\x00\\x00\\x00\\x00', b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00')",
            "",
            "class McapROS2DecodeError(Exception):",
            "    '''Raised when a CDR envelope cannot be decoded.'''",
            "",
            "_SENTINEL = object()",
            "",
            "def _iter_array_values(value):",
            "    '''Yield scalar values from a potentially nested array-like value.'''",
            "    for item in value:",
            "        if isinstance(item, collections.abc.Iterable) and not isinstance(",
            "            item, (bytes, bytearray, str, memoryview)",
            "        ):",
            "            yield from _iter_array_values(item)",
            "        else:",
            "            yield item",
            "",
            "def _to_packed_bytes(value, code, endianness='<', expected_length=None):",
            "    '''Pack an array-like value into raw bytes using only the stdlib.'''",
            "    if code == '?':",
            "        packed_bytes = bytes(1 if item else 0 for item in _iter_array_values(value))",
            "        if expected_length is not None and len(packed_bytes) != expected_length:",
            "            raise ValueError(",
            (
                "                f'fixed array expected {expected_length} elements, "
                "got {len(packed_bytes)}'"
            ),
            "            )",
            "        return packed_bytes",
            "    try:",
            "        packed = array.array(code, value)",
            "    except (TypeError, ValueError):",
            "        packed = array.array(code, _iter_array_values(value))",
            "    if expected_length is not None and len(packed) != expected_length:",
            "        raise ValueError(",
            "            f'fixed array expected {expected_length} elements, got {len(packed)}'",
            "        )",
            "    native_endianness = '<' if sys.byteorder == 'little' else '>'",
            "    if code not in {'b', 'B'} and endianness != native_endianness:",
            "        packed.byteswap()",
            "    return packed.tobytes()",
            "",
            "def _array_length(value):",
            "    '''Return the number of serialized primitive elements.'''",
            "    try:",
            "        view = memoryview(value)",
            "    except TypeError:",
            "        return len(value)",
            "    return view.nbytes // view.itemsize",
            "",
            "def _get_field(obj, f, default):",
            "    '''Get field from object (dict or attribute) with default.'''",
            "    if isinstance(obj, dict):",
            "        value = obj.get(f, default)",
            "        return default if value is None else value",
            "    value = getattr(obj, f, _SENTINEL)",
            "    if value is _SENTINEL:",
            "        return default",
            "    return default if value is None else value",
            "",
        ]
    )

    # Add global struct patterns
    generated_lines.append("# Global struct patterns")

    # Decoder struct patterns (unpack_from)
    for pattern, var_name in all_decoder_struct_patterns.items():
        generated_lines.append(f"{var_name} = struct.Struct('{pattern}').unpack_from")

    # Encoder struct patterns (pack)
    for pattern, var_name in all_encoder_struct_patterns.items():
        generated_lines.append(f"{var_name} = struct.Struct('{pattern}').pack")

    generated_lines.append("")

    # Add message class definitions (avoid duplicates)
    generated_lines.append("# Message class definitions")
    seen_class_names = set()
    for msg_class in sorted(all_message_classes, key=lambda x: x.__name__):
        class_name = msg_class.__name__
        if class_name not in seen_class_names:
            seen_class_names.add(class_name)
            generated_lines.extend(generate_class_definition(msg_class))
    generated_lines.append("")

    # Add decoder functions (both little and big-endian)
    generated_lines.append("# Decoder functions (little-endian)")
    for code in decoder_functions_le:
        generated_lines.append(code)
        generated_lines.append("")

    generated_lines.append("# Decoder functions (big-endian)")
    for code in decoder_functions_be:
        generated_lines.append(code)
        generated_lines.append("")

    generated_lines.append("# Decoder dispatchers (auto-detect endianness from CDR header)")
    for code in decoder_dispatchers:
        generated_lines.append(code)
        generated_lines.append("")

    # Add encoder functions
    generated_lines.append("# Encoder functions")
    for code in encoder_functions:
        generated_lines.append(code)
        generated_lines.append("")

    # Add decoder registry
    generated_lines.append("# Decoder registry")
    generated_lines.append("DECODERS = {")
    for schema_name in sorted(seen_schemas):
        func_name = f"decode_{schema_name.replace('/', '_')}"
        generated_lines.append(f'    "{schema_name}": {func_name},')
    generated_lines.append("}")
    generated_lines.append("")

    # Add encoder registry
    generated_lines.append("# Encoder registry")
    generated_lines.append("ENCODERS = {")
    for schema_name in sorted(seen_schemas):
        func_name = f"encode_{schema_name.replace('/', '_')}"
        generated_lines.append(f'    "{schema_name}": {func_name},')
    generated_lines.append("}")
    generated_lines.append("")

    # Add factory functions
    generated_lines.extend(
        [
            "def get_decoder(schema_name: str):",
            "    return DECODERS.get(schema_name)",
            "",
            "def get_encoder(schema_name: str):",
            "    return ENCODERS.get(schema_name)",
            "",
        ]
    )

    # Write the complete file
    output_path.write_text("\n".join(generated_lines), encoding="utf-8")


def generate_class_definition(msg_class: type) -> list[str]:
    """Generate Python class definition for a message class."""
    lines = []

    # Extract class information
    class_name = msg_class.__name__
    slots = getattr(msg_class, "__slots__", [])
    type_info = getattr(msg_class, "_type", "unknown")
    full_text = getattr(msg_class, "_full_text", "")
    fields_and_field_types = getattr(msg_class, "_fields_and_field_types", {})

    # Start class definition
    lines.append("@dataclasses.dataclass(slots=True)")
    lines.append(f"class {class_name}:")
    lines.append(f'    """Generated message class for {class_name}."""')
    lines.append(f"    _type: typing.ClassVar[str] = {type_info!r}")
    lines.append(f"    _full_text: typing.ClassVar[str] = {full_text!r}")
    lines.append(
        f"    _fields_and_field_types: typing.ClassVar[dict[str, str]] = {fields_and_field_types!r}"
    )
    lines.extend(f'    {slot}: "typing.Any"' for slot in slots)
    lines.append("")
    lines.append("    @classmethod")
    lines.append("    def get_fields_and_field_types(cls) -> dict[str, str]:")
    lines.append("        from copy import copy")
    lines.append("        return copy(cls._fields_and_field_types)")

    lines.append("")

    return lines


if __name__ == "__main__":
    main()
