"""Generate decoding code of a schema inside a MCAP.

Usage:
uv run python -m mcap_ros2_support_fast.scripts.generate_code <mcap_file> -o output.py
"""

import argparse
from pathlib import Path

from mcap.reader import make_reader

from mcap_ros2_support_fast._dynamic_codegen import UTF8_FUNC_NAME, CodeGeneratorFactory
from mcap_ros2_support_fast._planner import generate_plans, optimize_plan


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mcap_file", help="MCAP file to read schemas from")
    parser.add_argument(
        "-o", "--output", required=True, help="Output python file to write generated code to"
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.parent.mkdir(exist_ok=True, parents=True)

    # Generate code for each schema
    factories = []
    seen_schemas: set[str] = set()
    decoder_functions = []

    with Path(args.mcap_file).open("rb") as f:
        reader = make_reader(f)
        summary = reader.get_summary()
        assert summary
        schemas = summary.schemas
        for schema in schemas.values():
            if schema.name in seen_schemas:
                continue
            seen_schemas.add(schema.name)
            plan = generate_plans(schema.name, schema.data.decode())
            optimized_plan = optimize_plan(plan)

            # Create factory for this schema
            factory = CodeGeneratorFactory(optimized_plan)
            func_name = f"decode_{schema.name.replace('/', '_')}"
            code = factory.generate_decoder_code(func_name)

            factories.append(factory)
            decoder_functions.append(code)

    # Extract information needed for code generation
    all_struct_patterns = {}
    all_message_classes = set()

    for factory in factories:
        all_struct_patterns.update(factory.struct_patterns)
        all_message_classes.update(factory.message_classes)

    # Start building the complete output file
    generated_lines = [
        "# ruff: noqa",
        '"""This file is autogenerated, do not edit."""',
        "",
        "# Imports",
        "import codecs",
        "import dataclasses",
        "import struct",
        "import typing",
        "",
    ]

    # Add utility function definitions
    generated_lines.extend(
        [
            "# Utility functions",
            f"{UTF8_FUNC_NAME} = codecs.utf_8_decode",
            "",
        ]
    )

    # Add global struct patterns
    generated_lines.append("# Global struct patterns")
    for pattern, var_name in all_struct_patterns.items():
        generated_lines.append(f"{var_name}g = struct.Struct('{pattern}').unpack_from")
    generated_lines.append("")

    # Add message class definitions (avoid duplicates)
    generated_lines.append("# Message class definitions")
    seen_class_names = set()
    for msg_class in sorted(all_message_classes, key=lambda x: x.__name__):
        class_name = msg_class.__name__
        if class_name not in seen_class_names:
            seen_class_names.add(class_name)
            generated_lines.extend(generate_class_definition(msg_class))
    generated_lines.append("")

    # Add decoder functions
    generated_lines.append("# Decoder functions")
    for code in decoder_functions:
        generated_lines.append(code)
        generated_lines.append("")

    # Add decoder registry
    generated_lines.append("# Decoder registry")
    generated_lines.append("DECODERS = {")
    for schema_name in sorted(seen_schemas):
        func_name = f"decode_{schema_name.replace('/', '_')}"
        generated_lines.append(f'    "{schema_name}": {func_name},')
    generated_lines.append("}")
    generated_lines.append("")

    # Add factory function
    generated_lines.extend(
        [
            "def get_decoder(schema_name: str):",
            "    return DECODERS.get(schema_name)",
            "",
        ]
    )

    # Write the complete file
    output_path.write_text("\n".join(generated_lines), encoding="utf-8")


def generate_class_definition(msg_class: type) -> list[str]:
    """Generate Python class definition for a message class."""
    lines = []

    # Extract class information
    class_name = msg_class.__name__
    slots = getattr(msg_class, "__slots__", [])
    type_info = getattr(msg_class, "_type", "unknown")
    full_text = getattr(msg_class, "_full_text", "")

    # Start class definition
    lines.append("@dataclasses.dataclass(slots=True)")
    lines.append(f"class {class_name}:")
    lines.append(f'    """Generated message class for {class_name}."""')
    lines.append(f"    _type: typing.ClassVar[str] = {type_info!r}")
    lines.append(f"    _full_text: typing.ClassVar[str] = {full_text!r}")
    lines.extend(f'    {slot}: "typing.Any"' for slot in slots)

    lines.append("")

    return lines


if __name__ == "__main__":
    main()
