# AUTO-GENERATED FILE - DO NOT EDIT
# This file is automatically generated from schemas/mcap_info.json
# To modify types, edit the JSON schema and regenerate using:
#   uv run jsonschema-gentypes --config pymcap-cli/jsonschema-gentypes.yaml
# Or run: pre-commit run jsonschema-gentypes --all-files


from typing import TypedDict
from typing_extensions import Required


class ChannelInfo(TypedDict, total=False):
    """
    ChannelInfo.

    Information about a channel.
    """

    id: Required[int]
    """ Required property """

    topic: Required[str]
    """ Required property """

    schema_id: Required[int]
    """ Required property """

    schema_name: str | None
    message_count: Required[int]
    """ Required property """

    size_bytes: int | None
    duration_ns: int | None
    hz: Required[int | float]
    """ Required property """

    hz_channel: int | float | None
    hz_median: int | float | None
    bytes_per_second: int | float | None
    bytes_per_second_median: int | float | None
    bytes_per_message: int | float | None
    messages_per_second_median: int | float | None
    message_distribution: Required[list[int]]
    """ Required property """



class ChunkOverlaps(TypedDict, total=False):
    """
    ChunkOverlaps.

    Chunk overlap information.
    """

    max_concurrent: Required[int]
    """ Required property """

    max_concurrent_bytes: Required[int]
    """ Required property """



class ChunksInfo(TypedDict, total=False):
    """
    ChunksInfo.

    Chunk-related information.
    """

    by_compression: Required[dict[str, "CompressionStats"]]
    """ Required property """

    overlaps: Required["ChunkOverlaps"]
    """
    ChunkOverlaps.

    Chunk overlap information.

    Required property
    """



class CompressionStats(TypedDict, total=False):
    """
    CompressionStats.

    Statistics for a specific compression type.
    """

    count: Required[int]
    """ Required property """

    compressed_size: Required[int]
    """ Required property """

    uncompressed_size: Required[int]
    """ Required property """

    compression_ratio: Required[int | float]
    """ Required property """

    message_count: Required[int]
    """ Required property """

    size_stats: Required["Stats"]
    """
    Stats.

    Statistics with minimum, average, and maximum values.

    Required property
    """

    duration_stats: Required["Stats"]
    """
    Stats.

    Statistics with minimum, average, and maximum values.

    Required property
    """



class FileInfo(TypedDict, total=False):
    """
    FileInfo.

    File metadata.
    """

    path: Required[str]
    """ Required property """

    size_bytes: Required[int]
    """ Required property """



class HeaderInfo(TypedDict, total=False):
    """
    HeaderInfo.

    MCAP header information.
    """

    library: Required[str]
    """ Required property """

    profile: Required[str]
    """ Required property """



class McapInfoOutput(TypedDict, total=False):
    """
    McapInfoOutput.

    Complete MCAP info output structure.
    """

    file: Required["FileInfo"]
    """
    FileInfo.

    File metadata.

    Required property
    """

    header: Required["HeaderInfo"]
    """
    HeaderInfo.

    MCAP header information.

    Required property
    """

    statistics: Required["StatisticsInfo"]
    """
    StatisticsInfo.

    MCAP statistics.

    Required property
    """

    chunks: Required["ChunksInfo"]
    """
    ChunksInfo.

    Chunk-related information.

    Required property
    """

    channels: Required[list["ChannelInfo"]]
    """ Required property """

    schemas: Required[list["SchemaInfo"]]
    """ Required property """

    message_distribution: Required["MessageDistribution"]
    """
    MessageDistribution.

    Message distribution across time buckets.

    Required property
    """



class MessageDistribution(TypedDict, total=False):
    """
    MessageDistribution.

    Message distribution across time buckets.
    """

    bucket_count: Required[int]
    """ Required property """

    bucket_duration_ns: Required[int]
    """ Required property """

    message_counts: Required[list[int]]
    """ Required property """

    max_count: Required[int]
    """ Required property """



class SchemaInfo(TypedDict, total=False):
    """
    SchemaInfo.

    Information about a schema.
    """

    id: Required[int]
    """ Required property """

    name: Required[str]
    """ Required property """



class StatisticsInfo(TypedDict, total=False):
    """
    StatisticsInfo.

    MCAP statistics.
    """

    message_count: Required[int]
    """ Required property """

    chunk_count: Required[int]
    """ Required property """

    channel_count: Required[int]
    """ Required property """

    attachment_count: Required[int]
    """ Required property """

    metadata_count: Required[int]
    """ Required property """

    message_start_time: Required[int]
    """ Required property """

    message_end_time: Required[int]
    """ Required property """

    duration_ns: Required[int]
    """ Required property """



class Stats(TypedDict, total=False):
    """
    Stats.

    Statistics with minimum, average, and maximum values.
    """

    minimum: Required[int | float]
    """ Required property """

    maximum: Required[int | float]
    """ Required property """

    average: Required[int | float]
    """ Required property """

    median: Required[int | float]
    """ Required property """

